//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnit
    {
        public BusinessUnit()
        {
            this.SalesOfficeServiceLocations = new HashSet<SalesOfficeServiceLocation>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<SalesOfficeServiceLocation> SalesOfficeServiceLocations { get; set; }
    }
}
