//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country_tbl
    {
        public country_tbl()
        {
            this.region_tbl = new HashSet<region_tbl>();
        }
    
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string ShortIsoCode { get; set; }
        public string LongIsoCode { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual ICollection<region_tbl> region_tbl { get; set; }
    }
}
