//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFinderLink
    {
        public int id { get; set; }
        public long ProductID { get; set; }
        public long TaxonomyID { get; set; }
    
        public virtual ProductFinder ProductFinder { get; set; }
        public virtual ProductFinderTaxonomy ProductFinderTaxonomy { get; set; }
    }
}
