//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFinder
    {
        public ProductFinder()
        {
            this.ProductFinderLinks = new HashSet<ProductFinderLink>();
        }
    
        public long id { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string Name { get; set; }
        public string AcidValue { get; set; }
        public string CloudPoint { get; set; }
        public string CMC { get; set; }
        public string Density { get; set; }
        public string DravesWetting { get; set; }
        public string FlashPoint { get; set; }
        public string FoamDensity { get; set; }
        public string FormAt25C { get; set; }
        public string FreeFattyAcid { get; set; }
        public string FreezePoint { get; set; }
        public string HLB { get; set; }
        public string HydroxylValue { get; set; }
        public string InsulationValue { get; set; }
        public string IntrafacialTension { get; set; }
        public string Kosher { get; set; }
        public string MolesOfEO { get; set; }
        public string MolesOfPO { get; set; }
        public string OH_Functionality { get; set; }
        public string PercentActive { get; set; }
        public string PourPoint { get; set; }
        public string Solids { get; set; }
        public string SpecificGravity { get; set; }
        public string SurfaceTension { get; set; }
        public string ThermalStability { get; set; }
        public string Triglycerides { get; set; }
        public string ViscosityAt25C { get; set; }
        public string VOC { get; set; }
        public string CanOrder { get; set; }
        public string ChemicalDescription { get; set; }
        public string AcidNumber { get; set; }
        public string ApproxTgC { get; set; }
        public string ViscosityAt200C { get; set; }
        public string ViscosityAtC { get; set; }
    
        public virtual ICollection<ProductFinderLink> ProductFinderLinks { get; set; }
    }
}
