//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFinderTaxonomy
    {
        public ProductFinderTaxonomy()
        {
            this.ProductFinderLinks = new HashSet<ProductFinderLink>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductFinderLink> ProductFinderLinks { get; set; }
    }
}
