//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class region_tbl
    {
        public long RegionId { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string AlphaCode { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual country_tbl country_tbl { get; set; }
    }
}
