//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stepan.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOfficeServiceLocation
    {
        public int id { get; set; }
        public int BusinessUnitID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public int SalesOfficeID { get; set; }
        public string Note { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual SalesOffice SalesOffice { get; set; }
    }
}
